// Question bank. `answer` must exactly match one of `choices`;
// choices are shuffled at runtime.
const QUESTIONS = {
  history: [
    { q: "In what year did Christopher Columbus first reach the Americas?", choices: ["1492", "1502", "1453", "1519"], answer: "1492", explain: "Columbus landed in the Bahamas on October 12, 1492." },
    { q: "Who was the first President of the United States?", choices: ["George Washington", "John Adams", "Thomas Jefferson", "Benjamin Franklin"], answer: "George Washington", explain: "Washington served two terms, from 1789 to 1797." },
    { q: "In which year was the Magna Carta sealed?", choices: ["1215", "1066", "1348", "1415"], answer: "1215", explain: "King John sealed it at Runnymede in June 1215." },
    { q: "Which civilization built Machu Picchu?", choices: ["Inca", "Maya", "Aztec", "Olmec"], answer: "Inca", explain: "It was built in the 15th century, probably as an estate for the Inca emperor Pachacuti." },
    { q: "In what year did the Berlin Wall fall?", choices: ["1989", "1991", "1985", "1961"], answer: "1989", explain: "The border crossings opened on November 9, 1989." },
    { q: "Who was the first emperor of a unified China?", choices: ["Qin Shi Huang", "Kublai Khan", "Emperor Wu of Han", "Emperor Taizong"], answer: "Qin Shi Huang", explain: "He unified China in 221 BC and founded the Qin dynasty." },
    { q: "Who won the Battle of Hastings in 1066?", choices: ["William the Conqueror", "Harold Godwinson", "Harald Hardrada", "Edward the Confessor"], answer: "William the Conqueror", explain: "William, Duke of Normandy, defeated King Harold II and became King of England." },
    { q: "In what year did the French Revolution begin?", choices: ["1789", "1776", "1815", "1848"], answer: "1789", explain: "The storming of the Bastille on July 14, 1789 is its symbolic start." },
    { q: "Which Wonder of the Ancient World stood in Alexandria, Egypt?", choices: ["The Lighthouse (Pharos)", "The Hanging Gardens", "The Colossus", "The Temple of Artemis"], answer: "The Lighthouse (Pharos)", explain: "The Pharos of Alexandria was one of the tallest structures of the ancient world." },
    { q: "Who wrote the Ninety-five Theses in 1517?", choices: ["Martin Luther", "John Calvin", "Ulrich Zwingli", "John Wycliffe"], answer: "Martin Luther", explain: "They are traditionally seen as the start of the Protestant Reformation." },
    { q: "Under which Korean king was the Hangul alphabet created?", choices: ["King Sejong the Great", "King Taejo", "King Jeongjo", "King Gwanggaeto"], answer: "King Sejong the Great", explain: "Hangul was proclaimed in 1446 as the Hunminjeongeum." },
    { q: "Who was the first person to walk on the Moon?", choices: ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "John Glenn"], answer: "Neil Armstrong", explain: "Armstrong stepped onto the Moon on July 20, 1969 during Apollo 11." },
    { q: "In what year was Julius Caesar assassinated?", choices: ["44 BC", "27 BC", "14 AD", "79 AD"], answer: "44 BC", explain: "He was killed on the Ides of March (March 15), 44 BC." },
    { q: "Which war was formally ended by the Treaty of Versailles?", choices: ["World War I", "World War II", "The Napoleonic Wars", "The Franco-Prussian War"], answer: "World War I", explain: "The treaty was signed on June 28, 1919." },
    { q: "Who was Britain's Prime Minister for most of World War II?", choices: ["Winston Churchill", "Neville Chamberlain", "Clement Attlee", "Anthony Eden"], answer: "Winston Churchill", explain: "Churchill led Britain from May 1940 to July 1945." },
    { q: "In which country did the Renaissance begin?", choices: ["Italy", "France", "England", "Spain"], answer: "Italy", explain: "It began in Florence in the 14th century." },
    { q: "Who introduced movable-type printing to Europe around 1440?", choices: ["Johannes Gutenberg", "William Caxton", "Leonardo da Vinci", "Galileo Galilei"], answer: "Johannes Gutenberg", explain: "His Gutenberg Bible was printed in Mainz around 1455." },
    { q: "In what year was the Korean War armistice signed?", choices: ["1953", "1950", "1945", "1961"], answer: "1953", explain: "The armistice was signed on July 27, 1953." },
    { q: "What was the capital of the Byzantine Empire?", choices: ["Constantinople", "Rome", "Athens", "Antioch"], answer: "Constantinople", explain: "Today it is Istanbul, Turkey. It fell to the Ottomans in 1453." },
    { q: "Admiral Yi Sun-sin is famous for which armored warships?", choices: ["Turtle ships", "Dragon ships", "Tiger ships", "Crane ships"], answer: "Turtle ships", explain: "The geobukseon helped Joseon defeat the Japanese navy in the 1590s." },
    { q: "Who was the first woman to win a Nobel Prize?", choices: ["Marie Curie", "Rosalind Franklin", "Florence Nightingale", "Ada Lovelace"], answer: "Marie Curie", explain: "She shared the 1903 Physics Prize and won the Chemistry Prize in 1911." },
    { q: "In what year was the US Declaration of Independence adopted?", choices: ["1776", "1783", "1787", "1765"], answer: "1776", explain: "The Continental Congress adopted it on July 4, 1776." },
    { q: "Which famous ship sank on its maiden voyage in 1912?", choices: ["Titanic", "Lusitania", "Britannic", "Mayflower"], answer: "Titanic", explain: "It struck an iceberg on April 14, 1912 and sank early the next morning." },
    { q: "Where was Napoleon finally defeated in 1815?", choices: ["Waterloo", "Austerlitz", "Trafalgar", "Leipzig"], answer: "Waterloo", explain: "He was exiled to Saint Helena afterward." },
    { q: "Who led India's nonviolent independence movement against British rule?", choices: ["Mahatma Gandhi", "Jawaharlal Nehru", "Subhas Chandra Bose", "B. R. Ambedkar"], answer: "Mahatma Gandhi", explain: "India gained independence in 1947." },
    { q: "Which empire was ruled by Suleiman the Magnificent?", choices: ["Ottoman Empire", "Persian Empire", "Mughal Empire", "Holy Roman Empire"], answer: "Ottoman Empire", explain: "He reigned from 1520 to 1566, the height of Ottoman power." },
    { q: "In what year did World War II end?", choices: ["1945", "1944", "1946", "1939"], answer: "1945", explain: "Germany surrendered in May 1945 and Japan in September 1945." },
    { q: "Which Egyptian queen allied with the Roman general Mark Antony?", choices: ["Cleopatra VII", "Nefertiti", "Hatshepsut", "Nefertari"], answer: "Cleopatra VII", explain: "They were defeated by Octavian at the Battle of Actium in 31 BC." },
    { q: "In which century did the Black Death sweep across Europe?", choices: ["14th century", "12th century", "16th century", "10th century"], answer: "14th century", explain: "It peaked between 1347 and 1351." },
    { q: "Which Macedonian king conquered the Persian Empire?", choices: ["Alexander the Great", "Philip II", "Darius III", "Leonidas"], answer: "Alexander the Great", explain: "He defeated Darius III and built an empire stretching to India." },
    { q: "The Meiji Restoration of 1868 took place in which country?", choices: ["Japan", "China", "Korea", "Thailand"], answer: "Japan", explain: "It restored imperial rule and began Japan's rapid modernization." },
    { q: "Who founded Korea's Joseon dynasty in 1392?", choices: ["Yi Seong-gye", "Wang Geon", "King Sejong", "Jumong"], answer: "Yi Seong-gye", explain: "He became King Taejo, and Joseon lasted until 1897." },
    { q: "The Cold War was mainly between the United States and which country?", choices: ["Soviet Union", "China", "Germany", "Cuba"], answer: "Soviet Union", explain: "It lasted from about 1947 until the USSR dissolved in 1991." },
    { q: "Which US President issued the Emancipation Proclamation?", choices: ["Abraham Lincoln", "Ulysses S. Grant", "Andrew Johnson", "Thomas Jefferson"], answer: "Abraham Lincoln", explain: "It took effect on January 1, 1863." },
    { q: "What was the capital city of the Aztec Empire?", choices: ["Tenochtitlan", "Cusco", "Chichen Itza", "Teotihuacan"], answer: "Tenochtitlan", explain: "Mexico City is built on its ruins." },
    { q: "In what year did Nelson Mandela become President of South Africa?", choices: ["1994", "1990", "1999", "1986"], answer: "1994", explain: "He was elected in the country's first fully democratic election." },
    { q: "Whose expedition was the first to sail around the world (1519–1522)?", choices: ["Ferdinand Magellan", "Vasco da Gama", "Francis Drake", "James Cook"], answer: "Ferdinand Magellan", explain: "Magellan died on the way; Juan Sebastián Elcano completed the voyage." },
    { q: "Where did the ancient Olympic Games take place?", choices: ["Olympia, Greece", "Athens, Greece", "Rome, Italy", "Sparta, Greece"], answer: "Olympia, Greece", explain: "According to tradition they began in 776 BC." },
  ],
  bible: [
    { q: "What is the first book of the Bible?", choices: ["Genesis", "Exodus", "Matthew", "Psalms"], answer: "Genesis", explain: "Genesis opens with \"In the beginning God created the heavens and the earth.\"" },
    { q: "On which day of creation did God rest?", choices: ["The seventh", "The sixth", "The first", "The tenth"], answer: "The seventh", explain: "Genesis 2:2 says God rested on the seventh day." },
    { q: "Who built the ark to survive the great flood?", choices: ["Noah", "Abraham", "Moses", "Enoch"], answer: "Noah", explain: "Genesis 6–9." },
    { q: "Who led the Israelites out of Egypt?", choices: ["Moses", "Joshua", "Aaron", "Joseph"], answer: "Moses", explain: "This is recorded in the book of Exodus." },
    { q: "Who defeated the giant Goliath?", choices: ["David", "Saul", "Samson", "Jonathan"], answer: "David", explain: "David used a sling and a stone (1 Samuel 17)." },
    { q: "In which town was Jesus born?", choices: ["Bethlehem", "Nazareth", "Jerusalem", "Capernaum"], answer: "Bethlehem", explain: "Matthew 2:1 and Luke 2:4–7." },
    { q: "How many apostles did Jesus choose?", choices: ["12", "7", "10", "70"], answer: "12", explain: "Luke 6:13 says He chose twelve and named them apostles." },
    { q: "Which disciple betrayed Jesus?", choices: ["Judas Iscariot", "Thomas", "Peter", "Matthew"], answer: "Judas Iscariot", explain: "He betrayed Jesus for thirty pieces of silver (Matthew 26:15)." },
    { q: "Which prophet was swallowed by a great fish?", choices: ["Jonah", "Elijah", "Jeremiah", "Ezekiel"], answer: "Jonah", explain: "He was inside the fish for three days and three nights (Jonah 1:17)." },
    { q: "Which disciple denied Jesus three times?", choices: ["Peter", "John", "Andrew", "James"], answer: "Peter", explain: "He denied Him before the rooster crowed (Luke 22:54–62)." },
    { q: "Who killed his brother Abel?", choices: ["Cain", "Seth", "Esau", "Lamech"], answer: "Cain", explain: "Genesis 4:8." },
    { q: "Which judge of Israel had great strength tied to his uncut hair?", choices: ["Samson", "Gideon", "Joshua", "Barak"], answer: "Samson", explain: "Judges 13–16." },
    { q: "Who was thrown into the lions' den?", choices: ["Daniel", "Shadrach", "Joseph", "Elisha"], answer: "Daniel", explain: "God shut the lions' mouths (Daniel 6)." },
    { q: "In which river was Jesus baptized?", choices: ["Jordan", "Nile", "Euphrates", "Tigris"], answer: "Jordan", explain: "Mark 1:9." },
    { q: "Who baptized Jesus?", choices: ["John the Baptist", "Peter", "Andrew", "Zechariah"], answer: "John the Baptist", explain: "Matthew 3:13–17." },
    { q: "Who was the father of Isaac?", choices: ["Abraham", "Jacob", "Lot", "Noah"], answer: "Abraham", explain: "Isaac was born to Abraham and Sarah in their old age (Genesis 21)." },
    { q: "How many sons did Jacob have?", choices: ["12", "10", "7", "13"], answer: "12", explain: "They became the forefathers of the twelve tribes of Israel." },
    { q: "Who gave Joseph his special coat?", choices: ["His father Jacob", "Pharaoh", "His brother Reuben", "Potiphar"], answer: "His father Jacob", explain: "Jacob (Israel) loved Joseph more than his other sons (Genesis 37:3)." },
    { q: "What is the last book of the Bible?", choices: ["Revelation", "Jude", "Malachi", "Acts"], answer: "Revelation", explain: "It was written by John on the island of Patmos." },
    { q: "Which verse is famously the shortest in most English Bibles?", choices: ["\"Jesus wept.\"", "\"Rejoice always.\"", "\"God is love.\"", "\"Pray continually.\""], answer: "\"Jesus wept.\"", explain: "John 11:35, at the tomb of Lazarus." },
    { q: "Which son of David was known for his great wisdom?", choices: ["Solomon", "Absalom", "Nathan", "Amnon"], answer: "Solomon", explain: "He asked God for wisdom (1 Kings 3)." },
    { q: "What was Saul of Tarsus later known as?", choices: ["Paul", "Silas", "Barnabas", "Timothy"], answer: "Paul", explain: "He became the apostle to the Gentiles (Acts 13:9)." },
    { q: "How many books are in the Protestant Bible?", choices: ["66", "73", "39", "27"], answer: "66", explain: "39 in the Old Testament and 27 in the New Testament." },
    { q: "The walls of which city fell after the Israelites marched around it?", choices: ["Jericho", "Jerusalem", "Babylon", "Nineveh"], answer: "Jericho", explain: "Joshua 6." },
    { q: "Where did Jesus perform His first miracle, turning water into wine?", choices: ["Cana", "Bethany", "Nazareth", "Jericho"], answer: "Cana", explain: "It happened at a wedding (John 2:1–11)." },
    { q: "On which mountain did Moses receive the Ten Commandments?", choices: ["Mount Sinai", "Mount Carmel", "Mount of Olives", "Mount Ararat"], answer: "Mount Sinai", explain: "Exodus 19–20." },
    { q: "Which queen saved the Jewish people from Haman's plot?", choices: ["Esther", "Jezebel", "Vashti", "The Queen of Sheba"], answer: "Esther", explain: "The book of Esther; the festival of Purim remembers it." },
    { q: "Who was Ruth's mother-in-law?", choices: ["Naomi", "Orpah", "Rachel", "Leah"], answer: "Naomi", explain: "Ruth said, \"Where you go I will go\" (Ruth 1:16)." },
    { q: "How many loaves and fish did Jesus use to feed the 5,000?", choices: ["5 loaves and 2 fish", "7 loaves and 3 fish", "2 loaves and 5 fish", "12 loaves and 2 fish"], answer: "5 loaves and 2 fish", explain: "Twelve baskets of leftovers were collected (Matthew 14:17–20)." },
    { q: "Who was the first king of Israel?", choices: ["Saul", "David", "Solomon", "Samuel"], answer: "Saul", explain: "He was anointed by the prophet Samuel (1 Samuel 10)." },
    { q: "Which Gospel writer does Paul call \"the beloved physician\"?", choices: ["Luke", "Mark", "Matthew", "John"], answer: "Luke", explain: "Colossians 4:14." },
    { q: "Who is the oldest person recorded in the Bible?", choices: ["Methuselah", "Adam", "Noah", "Enoch"], answer: "Methuselah", explain: "He lived 969 years (Genesis 5:27)." },
    { q: "Which book of the Bible contains 150 songs and poems?", choices: ["Psalms", "Proverbs", "Song of Songs", "Lamentations"], answer: "Psalms", explain: "Many psalms are attributed to King David." },
    { q: "Which tax collector climbed a sycamore tree to see Jesus?", choices: ["Zacchaeus", "Matthew", "Nicodemus", "Bartimaeus"], answer: "Zacchaeus", explain: "Luke 19:1–10." },
    { q: "On the road to which city did Saul (Paul) encounter Jesus?", choices: ["Damascus", "Jerusalem", "Antioch", "Emmaus"], answer: "Damascus", explain: "Acts 9:1–19." },
    { q: "Who was Moses' brother?", choices: ["Aaron", "Joshua", "Caleb", "Levi"], answer: "Aaron", explain: "Aaron became Israel's first high priest." },
    { q: "In which parable does a stranger help a man beaten by robbers?", choices: ["The Good Samaritan", "The Prodigal Son", "The Lost Sheep", "The Sower"], answer: "The Good Samaritan", explain: "Luke 10:25–37." },
    { q: "How many plagues did God send on Egypt?", choices: ["10", "7", "12", "40"], answer: "10", explain: "Exodus 7–12." },
    { q: "Which prophet was taken up to heaven in a whirlwind?", choices: ["Elijah", "Elisha", "Isaiah", "Samuel"], answer: "Elijah", explain: "A chariot of fire appeared (2 Kings 2:11)." },
    { q: "In which garden did Jesus pray before His arrest?", choices: ["Gethsemane", "Eden", "Golgotha", "Bethany"], answer: "Gethsemane", explain: "Matthew 26:36." },
    { q: "Which book records the coming of the Holy Spirit at Pentecost?", choices: ["Acts", "Romans", "John", "Hebrews"], answer: "Acts", explain: "Acts 2:1–4." },
  ],
};
