// Question bank.
// Each question: { lvl, en: [question, choices, explanation], ko: [...] }
//   lvl 1 = easy, 2 = hard.
//   The FIRST choice is always the correct answer; choices are shuffled at runtime.
const QUESTIONS = {
  history: [
    // ---------- Easy ----------
    { lvl: 1,
      en: ["In what year did Christopher Columbus first reach the Americas?", ["1492", "1502", "1453", "1519"], "Columbus landed in the Bahamas on October 12, 1492."],
      ko: ["크리스토퍼 콜럼버스가 아메리카 대륙에 처음 도착한 해는?", ["1492년", "1502년", "1453년", "1519년"], "콜럼버스는 1492년 10월 12일 바하마 제도에 상륙했습니다."] },
    { lvl: 1,
      en: ["Who was the first President of the United States?", ["George Washington", "John Adams", "Thomas Jefferson", "Benjamin Franklin"], "Washington served two terms, from 1789 to 1797."],
      ko: ["미국의 초대 대통령은?", ["조지 워싱턴", "존 애덤스", "토머스 제퍼슨", "벤저민 프랭클린"], "워싱턴은 1789년부터 1797년까지 두 번 재임했습니다."] },
    { lvl: 1,
      en: ["In which year was the Magna Carta sealed?", ["1215", "1066", "1348", "1415"], "King John sealed it at Runnymede in June 1215."],
      ko: ["마그나 카르타(대헌장)가 승인된 해는?", ["1215년", "1066년", "1348년", "1415년"], "존 왕이 1215년 6월 러니미드에서 승인했습니다."] },
    { lvl: 1,
      en: ["Which civilization built Machu Picchu?", ["Inca", "Maya", "Aztec", "Olmec"], "It was built in the 15th century, probably as an estate for the Inca emperor Pachacuti."],
      ko: ["마추픽추를 건설한 문명은?", ["잉카", "마야", "아즈텍", "올멕"], "15세기에 잉카 황제 파차쿠티의 별궁으로 지어진 것으로 보입니다."] },
    { lvl: 1,
      en: ["In what year did the Berlin Wall fall?", ["1989", "1991", "1985", "1961"], "The border crossings opened on November 9, 1989."],
      ko: ["베를린 장벽이 무너진 해는?", ["1989년", "1991년", "1985년", "1961년"], "1989년 11월 9일 국경 검문소가 열렸습니다."] },
    { lvl: 1,
      en: ["Who was the first emperor of a unified China?", ["Qin Shi Huang", "Kublai Khan", "Emperor Wu of Han", "Emperor Taizong"], "He unified China in 221 BC and founded the Qin dynasty."],
      ko: ["중국을 최초로 통일한 황제는?", ["진시황", "쿠빌라이 칸", "한 무제", "당 태종"], "기원전 221년 중국을 통일하고 진나라를 세웠습니다."] },
    { lvl: 1,
      en: ["Who won the Battle of Hastings in 1066?", ["William the Conqueror", "Harold Godwinson", "Harald Hardrada", "Edward the Confessor"], "William, Duke of Normandy, defeated King Harold II and became King of England."],
      ko: ["1066년 헤이스팅스 전투의 승자는?", ["정복왕 윌리엄", "해럴드 고드윈슨", "하랄 하르드라다", "참회왕 에드워드"], "노르망디 공 윌리엄이 해럴드 2세를 꺾고 잉글랜드 왕이 되었습니다."] },
    { lvl: 1,
      en: ["In what year did the French Revolution begin?", ["1789", "1776", "1815", "1848"], "The storming of the Bastille on July 14, 1789 is its symbolic start."],
      ko: ["프랑스 혁명이 시작된 해는?", ["1789년", "1776년", "1815년", "1848년"], "1789년 7월 14일 바스티유 습격이 상징적인 시작입니다."] },
    { lvl: 1,
      en: ["Which Wonder of the Ancient World stood in Alexandria, Egypt?", ["The Lighthouse (Pharos)", "The Hanging Gardens", "The Colossus", "The Temple of Artemis"], "The Pharos of Alexandria was one of the tallest structures of the ancient world."],
      ko: ["이집트 알렉산드리아에 있던 고대 세계 7대 불가사의는?", ["파로스 등대", "바빌론의 공중 정원", "로도스의 거상", "아르테미스 신전"], "파로스 등대는 고대 세계에서 가장 높은 건축물 중 하나였습니다."] },
    { lvl: 1,
      en: ["Who wrote the Ninety-five Theses in 1517?", ["Martin Luther", "John Calvin", "Ulrich Zwingli", "John Wycliffe"], "They are traditionally seen as the start of the Protestant Reformation."],
      ko: ["1517년 95개조 논제를 발표한 사람은?", ["마르틴 루터", "장 칼뱅", "울리히 츠빙글리", "존 위클리프"], "흔히 종교개혁의 시작으로 여겨집니다."] },
    { lvl: 1,
      en: ["Under which Korean king was the Hangul alphabet created?", ["King Sejong the Great", "King Taejo", "King Jeongjo", "King Gwanggaeto"], "Hangul was proclaimed in 1446 as the Hunminjeongeum."],
      ko: ["한글을 창제한 왕은?", ["세종대왕", "태조", "정조", "광개토대왕"], "1446년 훈민정음으로 반포되었습니다."] },
    { lvl: 1,
      en: ["Who was the first person to walk on the Moon?", ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "John Glenn"], "Armstrong stepped onto the Moon on July 20, 1969 during Apollo 11."],
      ko: ["달에 처음 발을 디딘 사람은?", ["닐 암스트롱", "버즈 올드린", "유리 가가린", "존 글렌"], "1969년 7월 20일 아폴로 11호 임무 중이었습니다."] },
    { lvl: 1,
      en: ["In what year was Julius Caesar assassinated?", ["44 BC", "27 BC", "14 AD", "79 AD"], "He was killed on the Ides of March (March 15), 44 BC."],
      ko: ["율리우스 카이사르가 암살된 해는?", ["기원전 44년", "기원전 27년", "서기 14년", "서기 79년"], "기원전 44년 3월 15일에 살해되었습니다."] },
    { lvl: 1,
      en: ["Which war was formally ended by the Treaty of Versailles?", ["World War I", "World War II", "The Napoleonic Wars", "The Franco-Prussian War"], "The treaty was signed on June 28, 1919."],
      ko: ["베르사유 조약으로 공식 종결된 전쟁은?", ["제1차 세계 대전", "제2차 세계 대전", "나폴레옹 전쟁", "프로이센–프랑스 전쟁"], "1919년 6월 28일 조인되었습니다."] },
    { lvl: 1,
      en: ["Who was Britain's Prime Minister for most of World War II?", ["Winston Churchill", "Neville Chamberlain", "Clement Attlee", "Anthony Eden"], "Churchill led Britain from May 1940 to July 1945."],
      ko: ["제2차 세계 대전 대부분 기간 동안 영국 총리는?", ["윈스턴 처칠", "네빌 체임벌린", "클레멘트 애틀리", "앤서니 이든"], "처칠은 1940년 5월부터 1945년 7월까지 영국을 이끌었습니다."] },
    { lvl: 1,
      en: ["In which country did the Renaissance begin?", ["Italy", "France", "England", "Spain"], "It began in Florence in the 14th century."],
      ko: ["르네상스가 시작된 나라는?", ["이탈리아", "프랑스", "영국", "스페인"], "14세기 피렌체에서 시작되었습니다."] },
    { lvl: 1,
      en: ["Who introduced movable-type printing to Europe around 1440?", ["Johannes Gutenberg", "William Caxton", "Leonardo da Vinci", "Galileo Galilei"], "His Gutenberg Bible was printed in Mainz around 1455."],
      ko: ["1440년경 유럽에 활판 인쇄술을 도입한 사람은?", ["요하네스 구텐베르크", "윌리엄 캑스턴", "레오나르도 다빈치", "갈릴레오 갈릴레이"], "구텐베르크 성경은 1455년경 마인츠에서 인쇄되었습니다."] },
    { lvl: 1,
      en: ["In what year was the Korean War armistice signed?", ["1953", "1950", "1945", "1961"], "The armistice was signed on July 27, 1953."],
      ko: ["6·25 전쟁 정전 협정이 체결된 해는?", ["1953년", "1950년", "1945년", "1961년"], "1953년 7월 27일 체결되었습니다."] },
    { lvl: 1,
      en: ["What was the capital of the Byzantine Empire?", ["Constantinople", "Rome", "Athens", "Antioch"], "Today it is Istanbul, Turkey."],
      ko: ["비잔틴 제국의 수도는?", ["콘스탄티노폴리스", "로마", "아테네", "안티오키아"], "지금의 튀르키예 이스탄불입니다."] },
    { lvl: 1,
      en: ["Admiral Yi Sun-sin is famous for which armored warships?", ["Turtle ships", "Dragon ships", "Tiger ships", "Crane ships"], "The geobukseon helped Joseon defeat the Japanese navy in the 1590s."],
      ko: ["이순신 장군의 유명한 철갑선은?", ["거북선", "용선", "호랑이선", "학선"], "거북선은 1590년대 일본 수군을 물리치는 데 큰 역할을 했습니다."] },
    { lvl: 1,
      en: ["Who was the first woman to win a Nobel Prize?", ["Marie Curie", "Rosalind Franklin", "Florence Nightingale", "Ada Lovelace"], "She shared the 1903 Physics Prize and won the Chemistry Prize in 1911."],
      ko: ["최초의 여성 노벨상 수상자는?", ["마리 퀴리", "로절린드 프랭클린", "플로렌스 나이팅게일", "에이다 러브레이스"], "1903년 물리학상을 공동 수상하고 1911년 화학상을 받았습니다."] },
    { lvl: 1,
      en: ["In what year was the US Declaration of Independence adopted?", ["1776", "1783", "1787", "1765"], "The Continental Congress adopted it on July 4, 1776."],
      ko: ["미국 독립 선언서가 채택된 해는?", ["1776년", "1783년", "1787년", "1765년"], "1776년 7월 4일 대륙회의에서 채택되었습니다."] },
    { lvl: 1,
      en: ["Which famous ship sank on its maiden voyage in 1912?", ["Titanic", "Lusitania", "Britannic", "Mayflower"], "It struck an iceberg on April 14, 1912 and sank early the next morning."],
      ko: ["1912년 첫 항해에서 침몰한 배는?", ["타이타닉호", "루시타니아호", "브리타닉호", "메이플라워호"], "1912년 4월 14일 빙산과 충돌해 다음 날 새벽 침몰했습니다."] },
    { lvl: 1,
      en: ["Where was Napoleon finally defeated in 1815?", ["Waterloo", "Austerlitz", "Trafalgar", "Leipzig"], "He was exiled to Saint Helena afterward."],
      ko: ["1815년 나폴레옹이 최종 패배한 곳은?", ["워털루", "아우스터리츠", "트라팔가르", "라이프치히"], "이후 세인트헬레나섬으로 유배되었습니다."] },
    { lvl: 1,
      en: ["Who led India's nonviolent independence movement against British rule?", ["Mahatma Gandhi", "Jawaharlal Nehru", "Subhas Chandra Bose", "B. R. Ambedkar"], "India gained independence in 1947."],
      ko: ["영국 통치에 맞선 인도의 비폭력 독립운동 지도자는?", ["마하트마 간디", "자와할랄 네루", "수바스 찬드라 보스", "B. R. 암베드카르"], "인도는 1947년 독립했습니다."] },
    { lvl: 1,
      en: ["Which empire was ruled by Suleiman the Magnificent?", ["Ottoman Empire", "Persian Empire", "Mughal Empire", "Holy Roman Empire"], "He reigned from 1520 to 1566, the height of Ottoman power."],
      ko: ["술레이만 대제가 다스린 제국은?", ["오스만 제국", "페르시아 제국", "무굴 제국", "신성 로마 제국"], "1520년부터 1566년까지 재위했으며 오스만 제국의 전성기였습니다."] },
    { lvl: 1,
      en: ["In what year did World War II end?", ["1945", "1944", "1946", "1939"], "Germany surrendered in May 1945 and Japan in September 1945."],
      ko: ["제2차 세계 대전이 끝난 해는?", ["1945년", "1944년", "1946년", "1939년"], "독일은 1945년 5월, 일본은 1945년 9월에 항복했습니다."] },
    { lvl: 1,
      en: ["Which Egyptian queen allied with the Roman general Mark Antony?", ["Cleopatra VII", "Nefertiti", "Hatshepsut", "Nefertari"], "They were defeated by Octavian at the Battle of Actium in 31 BC."],
      ko: ["로마 장군 마르쿠스 안토니우스와 동맹을 맺은 이집트 여왕은?", ["클레오파트라 7세", "네페르티티", "하트셉수트", "네페르타리"], "기원전 31년 악티움 해전에서 옥타비아누스에게 패배했습니다."] },
    { lvl: 1,
      en: ["In which century did the Black Death sweep across Europe?", ["14th century", "12th century", "16th century", "10th century"], "It peaked between 1347 and 1351."],
      ko: ["흑사병이 유럽을 휩쓴 세기는?", ["14세기", "12세기", "16세기", "10세기"], "1347년부터 1351년 사이에 절정에 달했습니다."] },
    { lvl: 1,
      en: ["Which Macedonian king conquered the Persian Empire?", ["Alexander the Great", "Philip II", "Darius III", "Leonidas"], "He defeated Darius III and built an empire stretching to India."],
      ko: ["페르시아 제국을 정복한 마케도니아 왕은?", ["알렉산드로스 대왕", "필리포스 2세", "다리우스 3세", "레오니다스"], "다리우스 3세를 물리치고 인도까지 이르는 제국을 세웠습니다."] },
    { lvl: 1,
      en: ["The Meiji Restoration of 1868 took place in which country?", ["Japan", "China", "Korea", "Thailand"], "It restored imperial rule and began Japan's rapid modernization."],
      ko: ["1868년 메이지 유신이 일어난 나라는?", ["일본", "중국", "한국", "태국"], "천황 중심 체제를 회복하고 급속한 근대화를 시작했습니다."] },
    { lvl: 1,
      en: ["Who founded Korea's Joseon dynasty in 1392?", ["Yi Seong-gye", "Wang Geon", "King Sejong", "Jumong"], "He became King Taejo, and Joseon lasted until 1897."],
      ko: ["1392년 조선을 건국한 사람은?", ["이성계", "왕건", "세종", "주몽"], "태조로 즉위했으며 조선은 1897년까지 이어졌습니다."] },
    { lvl: 1,
      en: ["The Cold War was mainly between the United States and which country?", ["Soviet Union", "China", "Germany", "Cuba"], "It lasted from about 1947 until the USSR dissolved in 1991."],
      ko: ["냉전은 주로 미국과 어느 나라 사이의 대립이었나요?", ["소련", "중국", "독일", "쿠바"], "1947년경부터 1991년 소련 해체까지 이어졌습니다."] },
    { lvl: 1,
      en: ["Which US President issued the Emancipation Proclamation?", ["Abraham Lincoln", "Ulysses S. Grant", "Andrew Johnson", "Thomas Jefferson"], "It took effect on January 1, 1863."],
      ko: ["노예 해방 선언을 발표한 미국 대통령은?", ["에이브러햄 링컨", "율리시스 S. 그랜트", "앤드루 존슨", "토머스 제퍼슨"], "1863년 1월 1일 발효되었습니다."] },
    { lvl: 1,
      en: ["What was the capital city of the Aztec Empire?", ["Tenochtitlan", "Cusco", "Chichen Itza", "Teotihuacan"], "Mexico City is built on its ruins."],
      ko: ["아즈텍 제국의 수도는?", ["테노치티틀란", "쿠스코", "치첸이트사", "테오티우아칸"], "멕시코시티가 그 유적 위에 세워졌습니다."] },
    { lvl: 1,
      en: ["In what year did Nelson Mandela become President of South Africa?", ["1994", "1990", "1999", "1986"], "He was elected in the country's first fully democratic election."],
      ko: ["넬슨 만델라가 남아프리카 공화국 대통령이 된 해는?", ["1994년", "1990년", "1999년", "1986년"], "남아공 최초의 완전한 민주 선거에서 당선되었습니다."] },
    { lvl: 1,
      en: ["Whose expedition was the first to sail around the world (1519–1522)?", ["Ferdinand Magellan", "Vasco da Gama", "Francis Drake", "James Cook"], "Magellan died on the way; Juan Sebastián Elcano completed the voyage."],
      ko: ["최초로 세계 일주 항해(1519–1522)에 성공한 탐험대를 이끈 사람은?", ["페르디난드 마젤란", "바스쿠 다 가마", "프랜시스 드레이크", "제임스 쿡"], "마젤란은 도중에 사망했고 후안 세바스티안 엘카노가 항해를 마쳤습니다."] },
    { lvl: 1,
      en: ["Where did the ancient Olympic Games take place?", ["Olympia, Greece", "Athens, Greece", "Rome, Italy", "Sparta, Greece"], "According to tradition they began in 776 BC."],
      ko: ["고대 올림픽이 열린 곳은?", ["그리스 올림피아", "그리스 아테네", "이탈리아 로마", "그리스 스파르타"], "전승에 따르면 기원전 776년에 시작되었습니다."] },

    // ---------- Hard ----------
    { lvl: 2,
      en: ["Which war was ended by the Peace of Westphalia in 1648?", ["The Thirty Years' War", "The Hundred Years' War", "The War of the Spanish Succession", "The Seven Years' War"], "It is often seen as the start of the modern system of sovereign states."],
      ko: ["1648년 베스트팔렌 조약으로 끝난 전쟁은?", ["30년 전쟁", "백년 전쟁", "스페인 왕위 계승 전쟁", "7년 전쟁"], "근대 주권 국가 체제의 출발점으로 평가됩니다."] },
    { lvl: 2,
      en: ["Who was the last emperor of the Western Roman Empire, deposed in 476?", ["Romulus Augustulus", "Constantine XI", "Theodosius I", "Justinian I"], "He was deposed by the Germanic general Odoacer."],
      ko: ["476년 폐위된 서로마 제국의 마지막 황제는?", ["로물루스 아우구스툴루스", "콘스탄티노스 11세", "테오도시우스 1세", "유스티니아누스 1세"], "게르만 장군 오도아케르에 의해 폐위되었습니다."] },
    { lvl: 2,
      en: ["Which Athenian general planned the Greek naval victory at Salamis (480 BC)?", ["Themistocles", "Pericles", "Miltiades", "Alcibiades"], "He lured the Persian fleet into the narrow straits."],
      ko: ["기원전 480년 살라미스 해전의 승리를 이끈 아테네 장군은?", ["테미스토클레스", "페리클레스", "밀티아데스", "알키비아데스"], "페르시아 함대를 좁은 해협으로 유인했습니다."] },
    { lvl: 2,
      en: ["In which country did the Taiping Rebellion (1850–1864) take place?", ["China", "Japan", "India", "Vietnam"], "It was one of the deadliest civil wars in history, with tens of millions of deaths."],
      ko: ["태평천국 운동(1850–1864)이 일어난 나라는?", ["중국", "일본", "인도", "베트남"], "수천만 명이 희생된 역사상 가장 참혹한 내전 중 하나입니다."] },
    { lvl: 2,
      en: ["Which Austrian statesman dominated the Congress of Vienna (1814–1815)?", ["Klemens von Metternich", "Otto von Bismarck", "Charles-Maurice de Talleyrand", "Viscount Castlereagh"], "The Congress redrew the map of Europe after Napoleon."],
      ko: ["빈 회의(1814–1815)를 주도한 오스트리아 정치가는?", ["클레멘스 폰 메테르니히", "오토 폰 비스마르크", "샤를 모리스 드 탈레랑", "캐슬레이 자작"], "나폴레옹 이후 유럽의 질서를 다시 짰습니다."] },
    { lvl: 2,
      en: ["Which Goguryeo general defeated the Sui army at the Battle of Salsu in 612?", ["Eulji Mundeok", "Gang Gam-chan", "Gyebaek", "Kim Yu-sin"], "He routed the huge invasion force sent by Emperor Yang of Sui."],
      ko: ["612년 살수 대첩에서 수나라 군대를 물리친 고구려 장군은?", ["을지문덕", "강감찬", "계백", "김유신"], "수 양제가 보낸 대군을 크게 무찔렀습니다."] },
    { lvl: 2,
      en: ["General Gang Gam-chan won the Battle of Gwiju (1019) against whom?", ["The Khitan (Liao)", "The Mongols", "The Jurchen (Jin)", "Japanese pirates"], "It was the decisive victory of the Goryeo–Khitan wars."],
      ko: ["강감찬 장군이 1019년 귀주 대첩에서 물리친 상대는?", ["거란(요)", "몽골", "여진(금)", "왜구"], "고려–거란 전쟁의 결정적인 승리였습니다."] },
    { lvl: 2,
      en: ["The Hanseatic League was a trading network centered mainly on which sea?", ["Baltic Sea", "Mediterranean Sea", "Black Sea", "Caspian Sea"], "Lübeck was its leading city."],
      ko: ["한자 동맹은 주로 어느 바다를 중심으로 한 무역 동맹이었나요?", ["발트해", "지중해", "흑해", "카스피해"], "뤼베크가 중심 도시였습니다."] },
    { lvl: 2,
      en: ["Which dynasty built most of the Great Wall of China that survives today?", ["Ming", "Qin", "Han", "Tang"], "The Ming rebuilt it on a large scale in brick and stone."],
      ko: ["오늘날 남아 있는 만리장성의 대부분을 쌓은 왕조는?", ["명", "진", "한", "당"], "명나라가 벽돌과 석재로 대대적으로 다시 쌓았습니다."] },
    { lvl: 2,
      en: ["In what year did Admiral Yi Sun-sin win the Battle of Hansan Island?", ["1592", "1597", "1598", "1605"], "He used the 'crane wing' formation. Myeongnyang was in 1597 and Noryang in 1598."],
      ko: ["이순신 장군이 한산도 대첩에서 승리한 해는?", ["1592년", "1597년", "1598년", "1605년"], "학익진을 펼쳐 승리했습니다. 명량 해전은 1597년, 노량 해전은 1598년입니다."] },
    { lvl: 2,
      en: ["The Code of Hammurabi comes from which civilization?", ["Babylonia", "Assyria", "The Hittites", "Phoenicia"], "It dates from about 1750 BC."],
      ko: ["함무라비 법전을 만든 문명은?", ["바빌로니아", "아시리아", "히타이트", "페니키아"], "기원전 1750년경에 만들어졌습니다."] },
    { lvl: 2,
      en: ["Who was the first Mughal emperor of India?", ["Babur", "Akbar", "Humayun", "Aurangzeb"], "He founded the empire after winning the First Battle of Panipat in 1526."],
      ko: ["인도 무굴 제국의 초대 황제는?", ["바부르", "악바르", "후마윤", "아우랑제브"], "1526년 제1차 파니파트 전투에서 승리한 뒤 제국을 세웠습니다."] },
    { lvl: 2,
      en: ["Through which 1905 treaty did Japan make Korea a protectorate?", ["The Eulsa Treaty", "The Treaty of Ganghwa", "The Treaty of Shimonoseki", "The Treaty of Portsmouth"], "It stripped the Korean Empire of its diplomatic rights. The Ganghwa Treaty dates from 1876."],
      ko: ["1905년 일본이 대한제국의 외교권을 빼앗은 조약은?", ["을사조약(을사늑약)", "강화도 조약", "시모노세키 조약", "포츠머스 조약"], "대한제국은 외교권을 빼앗겼습니다. 강화도 조약은 1876년에 맺어졌습니다."] },
    { lvl: 2,
      en: ["Which Byzantine emperor built the Hagia Sophia, completed in 537?", ["Justinian I", "Constantine I", "Theodosius II", "Basil II"], "It was the world's largest cathedral for nearly a thousand years."],
      ko: ["537년 완공된 하기아 소피아를 세운 비잔틴 황제는?", ["유스티니아누스 1세", "콘스탄티누스 1세", "테오도시우스 2세", "바실리오스 2세"], "거의 천 년 동안 세계에서 가장 큰 성당이었습니다."] },
    { lvl: 2,
      en: ["In what year did Constantinople fall to the Ottoman Turks?", ["1453", "1204", "1492", "1389"], "Sultan Mehmed II took the city. In 1204 it was sacked by the Fourth Crusade."],
      ko: ["콘스탄티노폴리스가 오스만 제국에 함락된 해는?", ["1453년", "1204년", "1492년", "1389년"], "술탄 메흐메트 2세가 함락했습니다. 1204년에는 제4차 십자군이 약탈했습니다."] },
    { lvl: 2,
      en: ["Which Frankish leader won the Battle of Tours in 732?", ["Charles Martel", "Charlemagne", "Pepin the Short", "Clovis I"], "He was Charlemagne's grandfather."],
      ko: ["732년 투르 전투에서 승리한 프랑크 지도자는?", ["카를 마르텔", "샤를마뉴", "피핀 3세", "클로비스 1세"], "샤를마뉴의 할아버지입니다."] },
    { lvl: 2,
      en: ["In what year did Korea's March 1st Independence Movement take place?", ["1919", "1910", "1945", "1905"], "The Provisional Government of the Republic of Korea was founded in Shanghai the same year."],
      ko: ["3·1 운동이 일어난 해는?", ["1919년", "1910년", "1945년", "1905년"], "같은 해 상하이에서 대한민국 임시정부가 수립되었습니다."] },
    { lvl: 2,
      en: ["Which was the first country to give all women the right to vote in national elections (1893)?", ["New Zealand", "Australia", "Finland", "United Kingdom"], "New Zealand was then a self-governing British colony."],
      ko: ["1893년 세계 최초로 모든 여성에게 국정 선거 투표권을 준 나라는?", ["뉴질랜드", "오스트레일리아", "핀란드", "영국"], "당시 뉴질랜드는 영국의 자치 식민지였습니다."] },
    { lvl: 2,
      en: ["Which country fought Qing China in the First Opium War (1839–1842)?", ["Britain", "France", "Portugal", "Japan"], "China ceded Hong Kong in the Treaty of Nanking."],
      ko: ["제1차 아편 전쟁(1839–1842)에서 청나라와 싸운 나라는?", ["영국", "프랑스", "포르투갈", "일본"], "난징 조약으로 청나라는 홍콩을 넘겨주었습니다."] },
    { lvl: 2,
      en: ["What is the oldest surviving book printed with movable metal type (Korea, 1377)?", ["Jikji", "Tripitaka Koreana", "Mugujeonggwang Dharani Sutra", "Hunminjeongeum Haerye"], "It predates the Gutenberg Bible by about 78 years and is kept in the National Library of France."],
      ko: ["1377년 인쇄된, 현존하는 가장 오래된 금속 활자본은?", ["직지심체요절", "팔만대장경", "무구정광대다라니경", "훈민정음 해례본"], "구텐베르크 성경보다 약 78년 앞서며 현재 프랑스 국립도서관에 있습니다."] },
  ],

  bible: [
    // ---------- Easy ----------
    { lvl: 1,
      en: ["What is the first book of the Bible?", ["Genesis", "Exodus", "Matthew", "Psalms"], "Genesis opens with “In the beginning God created the heavens and the earth.”"],
      ko: ["성경의 첫 번째 책은?", ["창세기", "출애굽기", "마태복음", "시편"], "“태초에 하나님이 천지를 창조하시니라”로 시작합니다."] },
    { lvl: 1,
      en: ["On which day of creation did God rest?", ["The seventh", "The sixth", "The first", "The tenth"], "Genesis 2:2."],
      ko: ["하나님이 안식하신 날은 창조의 몇째 날인가요?", ["일곱째 날", "여섯째 날", "첫째 날", "열째 날"], "창세기 2:2."] },
    { lvl: 1,
      en: ["What did God create on the first day?", ["Light", "The sun and moon", "The seas", "Plants"], "“Let there be light” (Genesis 1:3–5)."],
      ko: ["창조 첫째 날 하나님이 만드신 것은?", ["빛", "해와 달", "바다", "식물"], "“빛이 있으라” (창 1:3–5)."] },
    { lvl: 1,
      en: ["Who built the ark to survive the great flood?", ["Noah", "Abraham", "Moses", "Enoch"], "Genesis 6–9."],
      ko: ["대홍수에서 살아남기 위해 방주를 만든 사람은?", ["노아", "아브라함", "모세", "에녹"], "창세기 6–9장."] },
    { lvl: 1,
      en: ["Who led the Israelites out of Egypt?", ["Moses", "Joshua", "Aaron", "Joseph"], "This is recorded in the book of Exodus."],
      ko: ["이스라엘 백성을 이끌고 애굽(이집트)을 나온 사람은?", ["모세", "여호수아", "아론", "요셉"], "출애굽기에 기록되어 있습니다."] },
    { lvl: 1,
      en: ["Who defeated the giant Goliath?", ["David", "Saul", "Samson", "Jonathan"], "David used a sling and a stone (1 Samuel 17)."],
      ko: ["거인 골리앗을 쓰러뜨린 사람은?", ["다윗", "사울", "삼손", "요나단"], "물매와 돌 하나로 이겼습니다 (삼상 17장)."] },
    { lvl: 1,
      en: ["In which town was Jesus born?", ["Bethlehem", "Nazareth", "Jerusalem", "Capernaum"], "Matthew 2:1 and Luke 2:4–7."],
      ko: ["예수님이 태어나신 마을은?", ["베들레헴", "나사렛", "예루살렘", "가버나움"], "마 2:1, 눅 2:4–7."] },
    { lvl: 1,
      en: ["How many apostles did Jesus choose?", ["12", "7", "10", "70"], "Luke 6:13 says He chose twelve and named them apostles."],
      ko: ["예수님이 택하신 사도는 몇 명인가요?", ["12명", "7명", "10명", "70명"], "열둘을 택하여 사도라 칭하셨습니다 (눅 6:13)."] },
    { lvl: 1,
      en: ["Which disciple betrayed Jesus?", ["Judas Iscariot", "Thomas", "Peter", "Matthew"], "He betrayed Jesus for thirty pieces of silver (Matthew 26:15)."],
      ko: ["예수님을 배신한 제자는?", ["가룟 유다", "도마", "베드로", "마태"], "은 삼십에 예수님을 넘겨주었습니다 (마 26:15)."] },
    { lvl: 1,
      en: ["Which prophet was swallowed by a great fish?", ["Jonah", "Elijah", "Jeremiah", "Ezekiel"], "He was inside the fish for three days and three nights (Jonah 1:17)."],
      ko: ["큰 물고기 뱃속에 들어간 선지자는?", ["요나", "엘리야", "예레미야", "에스겔"], "삼 일 밤낮을 물고기 뱃속에 있었습니다 (욘 1:17)."] },
    { lvl: 1,
      en: ["Which disciple denied Jesus three times?", ["Peter", "John", "Andrew", "James"], "He denied Him before the rooster crowed (Luke 22:54–62)."],
      ko: ["예수님을 세 번 부인한 제자는?", ["베드로", "요한", "안드레", "야고보"], "닭이 울기 전에 세 번 부인했습니다 (눅 22:54–62)."] },
    { lvl: 1,
      en: ["Who killed his brother Abel?", ["Cain", "Seth", "Esau", "Lamech"], "Genesis 4:8."],
      ko: ["동생 아벨을 죽인 사람은?", ["가인", "셋", "에서", "라멕"], "창세기 4:8."] },
    { lvl: 1,
      en: ["Which judge of Israel had great strength tied to his uncut hair?", ["Samson", "Gideon", "Joshua", "Barak"], "Judges 13–16."],
      ko: ["자르지 않은 머리카락과 큰 힘으로 유명한 사사는?", ["삼손", "기드온", "여호수아", "바락"], "사사기 13–16장."] },
    { lvl: 1,
      en: ["Who was thrown into the lions' den?", ["Daniel", "Shadrach", "Joseph", "Elisha"], "God shut the lions' mouths (Daniel 6)."],
      ko: ["사자 굴에 던져진 사람은?", ["다니엘", "사드락", "요셉", "엘리사"], "하나님이 사자들의 입을 막으셨습니다 (단 6장)."] },
    { lvl: 1,
      en: ["In which river was Jesus baptized?", ["Jordan", "Nile", "Euphrates", "Tigris"], "Mark 1:9."],
      ko: ["예수님이 세례를 받으신 강은?", ["요단강", "나일강", "유브라데강", "힛데겔강"], "마가복음 1:9."] },
    { lvl: 1,
      en: ["Who baptized Jesus?", ["John the Baptist", "Peter", "Andrew", "Zechariah"], "Matthew 3:13–17."],
      ko: ["예수님께 세례를 베푼 사람은?", ["세례 요한", "베드로", "안드레", "사가랴"], "마태복음 3:13–17."] },
    { lvl: 1,
      en: ["Who was the father of Isaac?", ["Abraham", "Jacob", "Lot", "Noah"], "Isaac was born to Abraham and Sarah in their old age (Genesis 21)."],
      ko: ["이삭의 아버지는?", ["아브라함", "야곱", "롯", "노아"], "아브라함과 사라가 늙어서 낳은 아들입니다 (창 21장)."] },
    { lvl: 1,
      en: ["How many sons did Jacob have?", ["12", "10", "7", "13"], "They became the forefathers of the twelve tribes of Israel."],
      ko: ["야곱의 아들은 몇 명인가요?", ["12명", "10명", "7명", "13명"], "이스라엘 열두 지파의 조상이 되었습니다."] },
    { lvl: 1,
      en: ["Who gave Joseph his special coat?", ["His father Jacob", "Pharaoh", "His brother Reuben", "Potiphar"], "Jacob (Israel) loved Joseph more than his other sons (Genesis 37:3)."],
      ko: ["요셉에게 채색옷을 지어 준 사람은?", ["아버지 야곱", "바로", "형 르우벤", "보디발"], "야곱(이스라엘)은 요셉을 다른 아들들보다 더 사랑했습니다 (창 37:3)."] },
    { lvl: 1,
      en: ["What is the last book of the Bible?", ["Revelation", "Jude", "Malachi", "Acts"], "It records the visions given to John."],
      ko: ["성경의 마지막 책은?", ["요한계시록", "유다서", "말라기", "사도행전"], "요한이 받은 계시를 기록한 책입니다."] },
    { lvl: 1,
      en: ["Which son of David was known for his great wisdom?", ["Solomon", "Absalom", "Nathan", "Amnon"], "He asked God for wisdom (1 Kings 3)."],
      ko: ["지혜로 유명한 다윗의 아들은?", ["솔로몬", "압살롬", "나단", "암논"], "하나님께 지혜를 구했습니다 (왕상 3장)."] },
    { lvl: 1,
      en: ["What was Saul of Tarsus later known as?", ["Paul", "Silas", "Barnabas", "Timothy"], "He became the apostle to the Gentiles (Acts 13:9)."],
      ko: ["다소 사람 사울의 다른 이름은?", ["바울", "실라", "바나바", "디모데"], "이방인의 사도가 되었습니다 (행 13:9)."] },
    { lvl: 1,
      en: ["How many books are in the Protestant Bible?", ["66", "73", "39", "27"], "39 in the Old Testament and 27 in the New Testament."],
      ko: ["개신교 성경은 모두 몇 권인가요?", ["66권", "73권", "39권", "27권"], "구약 39권, 신약 27권입니다."] },
    { lvl: 1,
      en: ["The walls of which city fell after the Israelites marched around it?", ["Jericho", "Jerusalem", "Babylon", "Nineveh"], "Joshua 6."],
      ko: ["이스라엘 백성이 돌자 성벽이 무너진 성은?", ["여리고", "예루살렘", "바벨론", "니느웨"], "여호수아 6장."] },
    { lvl: 1,
      en: ["Where did Jesus perform His first miracle, turning water into wine?", ["Cana", "Bethany", "Nazareth", "Jericho"], "It happened at a wedding (John 2:1–11)."],
      ko: ["예수님이 물로 포도주를 만드신 첫 표적의 장소는?", ["가나", "베다니", "나사렛", "여리고"], "혼인 잔치에서 일어났습니다 (요 2:1–11)."] },
    { lvl: 1,
      en: ["On which mountain did Moses receive the Ten Commandments?", ["Mount Sinai", "Mount Carmel", "Mount of Olives", "Mount Ararat"], "Exodus 19–20."],
      ko: ["모세가 십계명을 받은 산은?", ["시내산", "갈멜산", "감람산", "아라랏산"], "출애굽기 19–20장."] },
    { lvl: 1,
      en: ["Which queen saved the Jewish people from Haman's plot?", ["Esther", "Jezebel", "Vashti", "The Queen of Sheba"], "The festival of Purim remembers it."],
      ko: ["하만의 음모에서 유다 민족을 구한 왕비는?", ["에스더", "이세벨", "와스디", "스바 여왕"], "부림절이 이 일을 기념합니다."] },
    { lvl: 1,
      en: ["Who was Ruth's mother-in-law?", ["Naomi", "Orpah", "Rachel", "Leah"], "Ruth said, “Where you go I will go” (Ruth 1:16)."],
      ko: ["룻의 시어머니는?", ["나오미", "오르바", "라헬", "레아"], "“어머니께서 가시는 곳에 나도 가고” (룻 1:16)."] },
    { lvl: 1,
      en: ["How many loaves and fish did Jesus use to feed the 5,000?", ["5 loaves and 2 fish", "7 loaves and 3 fish", "2 loaves and 5 fish", "12 loaves and 2 fish"], "Twelve baskets of leftovers were collected (Matthew 14:17–20)."],
      ko: ["오천 명을 먹이실 때 사용하신 떡과 물고기는?", ["떡 다섯 개와 물고기 두 마리", "떡 일곱 개와 물고기 세 마리", "떡 두 개와 물고기 다섯 마리", "떡 열두 개와 물고기 두 마리"], "남은 조각이 열두 바구니에 찼습니다 (마 14:17–20)."] },
    { lvl: 1,
      en: ["Who was the first king of Israel?", ["Saul", "David", "Solomon", "Samuel"], "He was chosen as king in 1 Samuel 10."],
      ko: ["이스라엘의 첫 번째 왕은?", ["사울", "다윗", "솔로몬", "사무엘"], "사무엘상 10장에서 왕으로 세워졌습니다."] },
    { lvl: 1,
      en: ["Which Gospel writer does Paul call “the beloved physician”?", ["Luke", "Mark", "Matthew", "John"], "Colossians 4:14."],
      ko: ["바울이 “사랑받는 의사”라고 부른 복음서 저자는?", ["누가", "마가", "마태", "요한"], "골로새서 4:14."] },
    { lvl: 1,
      en: ["Who is the oldest person recorded in the Bible?", ["Methuselah", "Adam", "Noah", "Enoch"], "He lived 969 years (Genesis 5:27)."],
      ko: ["성경에서 가장 오래 산 사람은?", ["므두셀라", "아담", "노아", "에녹"], "969세까지 살았습니다 (창 5:27)."] },
    { lvl: 1,
      en: ["Which book of the Bible contains 150 songs and poems?", ["Psalms", "Proverbs", "Song of Songs", "Lamentations"], "Many psalms are attributed to King David."],
      ko: ["150편의 노래와 시가 담긴 성경은?", ["시편", "잠언", "아가", "예레미야애가"], "많은 시가 다윗의 시로 전해집니다."] },
    { lvl: 1,
      en: ["Which tax collector climbed a sycamore tree to see Jesus?", ["Zacchaeus", "Matthew", "Nicodemus", "Bartimaeus"], "Luke 19:1–10."],
      ko: ["예수님을 보려고 뽕나무에 올라간 세리장은?", ["삭개오", "마태", "니고데모", "바디매오"], "누가복음 19:1–10."] },
    { lvl: 1,
      en: ["On the road to which city did Saul (Paul) encounter Jesus?", ["Damascus", "Jerusalem", "Antioch", "Emmaus"], "Acts 9:1–19."],
      ko: ["사울(바울)이 어느 도시로 가는 길에 예수님을 만났나요?", ["다메섹", "예루살렘", "안디옥", "엠마오"], "사도행전 9:1–19."] },
    { lvl: 1,
      en: ["Who was Moses' brother?", ["Aaron", "Joshua", "Caleb", "Levi"], "Aaron became Israel's first high priest."],
      ko: ["모세의 형은?", ["아론", "여호수아", "갈렙", "레위"], "아론은 이스라엘의 첫 대제사장이 되었습니다."] },
    { lvl: 1,
      en: ["In which parable does a stranger help a man beaten by robbers?", ["The Good Samaritan", "The Prodigal Son", "The Lost Sheep", "The Sower"], "Luke 10:25–37."],
      ko: ["강도 만난 사람을 도와준 이야기가 나오는 비유는?", ["선한 사마리아인", "탕자", "잃은 양", "씨 뿌리는 자"], "누가복음 10:25–37."] },
    { lvl: 1,
      en: ["How many plagues did God send on Egypt?", ["10", "7", "12", "40"], "Exodus 7–12."],
      ko: ["하나님이 애굽에 내리신 재앙은 몇 가지인가요?", ["10가지", "7가지", "12가지", "40가지"], "출애굽기 7–12장."] },
    { lvl: 1,
      en: ["Which prophet was taken up to heaven in a whirlwind?", ["Elijah", "Elisha", "Isaiah", "Samuel"], "A chariot of fire appeared (2 Kings 2:11)."],
      ko: ["회오리바람을 타고 하늘로 올라간 선지자는?", ["엘리야", "엘리사", "이사야", "사무엘"], "불수레와 불말들이 나타났습니다 (왕하 2:11)."] },
    { lvl: 1,
      en: ["In which garden did Jesus pray before His arrest?", ["Gethsemane", "Eden", "Golgotha", "Bethany"], "Matthew 26:36."],
      ko: ["예수님이 잡히시기 전 기도하신 곳은?", ["겟세마네", "에덴", "골고다", "베다니"], "마태복음 26:36."] },
    { lvl: 1,
      en: ["Which book records the coming of the Holy Spirit at Pentecost?", ["Acts", "Romans", "John", "Hebrews"], "Acts 2:1–4."],
      ko: ["오순절 성령 강림을 기록한 책은?", ["사도행전", "로마서", "요한복음", "히브리서"], "사도행전 2:1–4."] },

    // ---------- Hard ----------
    { lvl: 2,
      en: ["Who was the father of John the Baptist?", ["Zechariah", "Zebedee", "Joseph", "Simeon"], "He was a priest serving in the temple (Luke 1:5–13)."],
      ko: ["세례 요한의 아버지는?", ["사가랴", "세베대", "요셉", "시므온"], "성전에서 섬기던 제사장이었습니다 (눅 1:5–13)."] },
    { lvl: 2,
      en: ["Which king of Babylon destroyed Solomon's temple in Jerusalem?", ["Nebuchadnezzar", "Cyrus", "Belshazzar", "Darius"], "2 Kings 25, around 586 BC."],
      ko: ["예루살렘의 솔로몬 성전을 파괴한 바벨론 왕은?", ["느부갓네살", "고레스", "벨사살", "다리오"], "열왕기하 25장, 기원전 586년경."] },
    { lvl: 2,
      en: ["Who was chosen to replace Judas as one of the Twelve?", ["Matthias", "Barnabas", "Silas", "Stephen"], "He was chosen by casting lots (Acts 1:26)."],
      ko: ["가룟 유다를 대신해 열두 사도가 된 사람은?", ["맛디아", "바나바", "실라", "스데반"], "제비뽑기로 뽑혔습니다 (행 1:26)."] },
    { lvl: 2,
      en: ["Who was the first Christian martyr?", ["Stephen", "James", "Philip", "Peter"], "He was stoned to death (Acts 7)."],
      ko: ["최초의 기독교 순교자는?", ["스데반", "야고보", "빌립", "베드로"], "돌에 맞아 순교했습니다 (행 7장)."] },
    { lvl: 2,
      en: ["For how many years did the Israelites wander in the wilderness?", ["40", "12", "70", "400"], "Numbers 14:33–34."],
      ko: ["이스라엘 백성이 광야에서 방황한 기간은?", ["40년", "12년", "70년", "400년"], "민수기 14:33–34."] },
    { lvl: 2,
      en: ["Which prophet anointed David as king?", ["Samuel", "Nathan", "Elijah", "Gad"], "1 Samuel 16."],
      ko: ["다윗에게 기름을 부어 왕으로 세운 선지자는?", ["사무엘", "나단", "엘리야", "갓"], "사무엘상 16장."] },
    { lvl: 2,
      en: ["Who was Sarah's Egyptian servant and the mother of Ishmael?", ["Hagar", "Bilhah", "Zilpah", "Keturah"], "Genesis 16."],
      ko: ["사라의 애굽인 여종이자 이스마엘의 어머니는?", ["하갈", "빌하", "실바", "그두라"], "창세기 16장."] },
    { lvl: 2,
      en: ["On which island was John when he received the visions of Revelation?", ["Patmos", "Cyprus", "Crete", "Malta"], "Revelation 1:9."],
      ko: ["요한이 요한계시록의 환상을 받은 섬은?", ["밧모", "구브로", "그레데", "멜리데"], "요한계시록 1:9."] },
    { lvl: 2,
      en: ["Which left-handed judge killed King Eglon of Moab?", ["Ehud", "Othniel", "Gideon", "Jephthah"], "Judges 3:12–30."],
      ko: ["모압 왕 에글론을 죽인 왼손잡이 사사는?", ["에훗", "옷니엘", "기드온", "입다"], "사사기 3:12–30."] },
    { lvl: 2,
      en: ["Which book comes right after Nehemiah in the Protestant Old Testament?", ["Esther", "Ezra", "Job", "Ruth"], "The order is Ezra, Nehemiah, Esther, Job."],
      ko: ["개신교 구약에서 느헤미야 바로 다음 책은?", ["에스더", "에스라", "욥기", "룻기"], "에스라–느헤미야–에스더–욥기 순서입니다."] },
    { lvl: 2,
      en: ["Which prophet was told to marry Gomer?", ["Hosea", "Amos", "Joel", "Micah"], "Hosea 1."],
      ko: ["고멜과 결혼하라는 명령을 받은 선지자는?", ["호세아", "아모스", "요엘", "미가"], "호세아 1장."] },
    { lvl: 2,
      en: ["Who was the high priest when Jesus was put on trial?", ["Caiaphas", "Gamaliel", "Eli", "Zadok"], "Matthew 26:57."],
      ko: ["예수님이 재판받으실 때의 대제사장은?", ["가야바", "가말리엘", "엘리", "사독"], "마태복음 26:57."] },
    { lvl: 2,
      en: ["What is the shortest book of the Old Testament?", ["Obadiah", "Jonah", "Haggai", "Ruth"], "It has just one chapter of 21 verses."],
      ko: ["구약에서 가장 짧은 책은?", ["오바댜", "요나", "학개", "룻기"], "단 1장 21절로 되어 있습니다."] },
    { lvl: 2,
      en: ["Paul praised the faith of Timothy's grandmother. What was her name?", ["Lois", "Eunice", "Lydia", "Priscilla"], "Eunice was Timothy's mother (2 Timothy 1:5)."],
      ko: ["바울이 믿음을 칭찬한 디모데의 외조모 이름은?", ["로이스", "유니게", "루디아", "브리스길라"], "유니게는 디모데의 어머니입니다 (딤후 1:5)."] },
    { lvl: 2,
      en: ["How many days did it take to rebuild Jerusalem's wall under Nehemiah?", ["52", "40", "70", "100"], "Nehemiah 6:15."],
      ko: ["느헤미야 때 예루살렘 성벽을 재건하는 데 걸린 기간은?", ["52일", "40일", "70일", "100일"], "느헤미야 6:15."] },
    { lvl: 2,
      en: ["Which king saw the handwriting on the wall?", ["Belshazzar", "Nebuchadnezzar", "Darius", "Cyrus"], "“Mene, mene, tekel, parsin” (Daniel 5)."],
      ko: ["벽에 나타난 손가락 글씨를 본 왕은?", ["벨사살", "느부갓네살", "다리오", "고레스"], "“메네 메네 데겔 우바르신” (단 5장)."] },
    { lvl: 2,
      en: ["Who was the mother of the prophet Samuel?", ["Hannah", "Peninnah", "Rachel", "Elizabeth"], "She prayed for a son at Shiloh (1 Samuel 1)."],
      ko: ["선지자 사무엘의 어머니는?", ["한나", "브닌나", "라헬", "엘리사벳"], "실로에서 아들을 달라고 기도했습니다 (삼상 1장)."] },
    { lvl: 2,
      en: ["In which city did Paul speak about an altar “to an unknown god”?", ["Athens", "Corinth", "Ephesus", "Rome"], "He spoke at the Areopagus (Acts 17:22–23)."],
      ko: ["바울이 “알지 못하는 신에게” 새긴 제단에 대해 설교한 도시는?", ["아덴(아테네)", "고린도", "에베소", "로마"], "아레오바고에서 설교했습니다 (행 17:22–23)."] },
    { lvl: 2,
      en: ["Which apostle was also called Didymus, meaning “the Twin”?", ["Thomas", "Bartholomew", "Thaddaeus", "Philip"], "John 11:16."],
      ko: ["“디두모”(쌍둥이)라고도 불린 사도는?", ["도마", "바돌로매", "다대오", "빌립"], "요한복음 11:16."] },
    { lvl: 2,
      en: ["How old was Abraham when Isaac was born?", ["100", "75", "90", "120"], "Genesis 21:5."],
      ko: ["이삭이 태어났을 때 아브라함의 나이는?", ["100세", "75세", "90세", "120세"], "창세기 21:5."] },
  ],

  geography: [
    // ---------- Easy ----------
    { lvl: 1,
      en: ["What is the largest ocean on Earth?", ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"], "It covers about a third of the Earth's surface."],
      ko: ["지구에서 가장 큰 대양은?", ["태평양", "대서양", "인도양", "북극해"], "지구 표면의 약 3분의 1을 차지합니다."] },
    { lvl: 1,
      en: ["What is the capital of Australia?", ["Canberra", "Sydney", "Melbourne", "Perth"], "It was built as a compromise between Sydney and Melbourne."],
      ko: ["오스트레일리아의 수도는?", ["캔버라", "시드니", "멜버른", "퍼스"], "시드니와 멜버른 사이의 타협으로 세워진 계획 도시입니다."] },
    { lvl: 1,
      en: ["Which river is traditionally called the longest in the world?", ["Nile", "Amazon", "Yangtze", "Mississippi"], "It is about 6,650 km long, though some measurements make the Amazon longer."],
      ko: ["전통적으로 세계에서 가장 긴 강으로 꼽히는 강은?", ["나일강", "아마존강", "양쯔강", "미시시피강"], "약 6,650 km이며, 아마존강이 더 길다는 측정도 있습니다."] },
    { lvl: 1,
      en: ["Which is the largest country by area?", ["Russia", "Canada", "China", "United States"], "It covers more than 17 million km²."],
      ko: ["면적이 가장 넓은 나라는?", ["러시아", "캐나다", "중국", "미국"], "1,700만 km²가 넘습니다."] },
    { lvl: 1,
      en: ["What is the highest mountain above sea level?", ["Mount Everest", "K2", "Kangchenjunga", "Kilimanjaro"], "It is 8,849 m high."],
      ko: ["해발 고도가 가장 높은 산은?", ["에베레스트산", "K2", "칸첸중가", "킬리만자로산"], "높이는 8,849 m입니다."] },
    { lvl: 1,
      en: ["What is the largest hot desert in the world?", ["Sahara", "Arabian Desert", "Gobi", "Kalahari"], "Counting cold deserts, Antarctica is the largest."],
      ko: ["세계에서 가장 큰 더운 사막은?", ["사하라 사막", "아라비아 사막", "고비 사막", "칼라하리 사막"], "추운 사막까지 포함하면 남극이 가장 큽니다."] },
    { lvl: 1,
      en: ["What is the capital of Canada?", ["Ottawa", "Toronto", "Vancouver", "Montreal"], "Ottawa is in the province of Ontario."],
      ko: ["캐나다의 수도는?", ["오타와", "토론토", "밴쿠버", "몬트리올"], "오타와는 온타리오주에 있습니다."] },
    { lvl: 1,
      en: ["How many continents are there in the most common model?", ["7", "5", "6", "8"], "Asia, Africa, North America, South America, Antarctica, Europe and Oceania."],
      ko: ["가장 흔한 구분법에서 대륙은 몇 개인가요?", ["7개", "5개", "6개", "8개"], "아시아, 아프리카, 북아메리카, 남아메리카, 남극, 유럽, 오세아니아입니다."] },
    { lvl: 1,
      en: ["Which country has the largest population?", ["India", "China", "United States", "Indonesia"], "India overtook China in 2023."],
      ko: ["인구가 가장 많은 나라는?", ["인도", "중국", "미국", "인도네시아"], "2023년 인도가 중국을 앞질렀습니다."] },
    { lvl: 1,
      en: ["What is the capital of Japan?", ["Tokyo", "Osaka", "Kyoto", "Yokohama"], "Kyoto was the imperial capital for over a thousand years before that."],
      ko: ["일본의 수도는?", ["도쿄", "오사카", "교토", "요코하마"], "그전에는 교토가 천 년 넘게 수도였습니다."] },
    { lvl: 1,
      en: ["What is the smallest country in the world?", ["Vatican City", "Monaco", "San Marino", "Liechtenstein"], "It covers about 0.44 km²."],
      ko: ["세계에서 가장 작은 나라는?", ["바티칸 시국", "모나코", "산마리노", "리히텐슈타인"], "면적이 약 0.44 km²입니다."] },
    { lvl: 1,
      en: ["On which continent is Egypt?", ["Africa", "Asia", "Europe", "South America"], "Only its Sinai Peninsula lies in Asia."],
      ko: ["이집트는 어느 대륙에 있나요?", ["아프리카", "아시아", "유럽", "남아메리카"], "시나이반도만 아시아에 속합니다."] },
    { lvl: 1,
      en: ["What is the highest mountain on the Korean Peninsula?", ["Baekdusan", "Hallasan", "Jirisan", "Seoraksan"], "It is 2,744 m. South Korea's highest is Hallasan (1,947 m)."],
      ko: ["한반도에서 가장 높은 산은?", ["백두산", "한라산", "지리산", "설악산"], "높이 2,744 m입니다. 남한의 최고봉은 한라산(1,947 m)입니다."] },
    { lvl: 1,
      en: ["What is South Korea's largest island?", ["Jeju Island", "Geoje Island", "Ganghwa Island", "Ulleung Island"], "Jeju is also home to Hallasan."],
      ko: ["대한민국에서 가장 큰 섬은?", ["제주도", "거제도", "강화도", "울릉도"], "한라산도 제주도에 있습니다."] },
    { lvl: 1,
      en: ["Which river flows through Seoul?", ["Han River", "Nakdong River", "Geum River", "Yeongsan River"], "It flows west into the Yellow Sea."],
      ko: ["서울을 가로지르는 강은?", ["한강", "낙동강", "금강", "영산강"], "서쪽으로 흘러 서해로 들어갑니다."] },
    { lvl: 1,
      en: ["The Equator passes through which of these countries?", ["Ecuador", "Egypt", "Mexico", "India"], "The country's name is Spanish for “equator.”"],
      ko: ["다음 중 적도가 지나는 나라는?", ["에콰도르", "이집트", "멕시코", "인도"], "나라 이름이 스페인어로 ‘적도’라는 뜻입니다."] },
    { lvl: 1,
      en: ["Which country is famously shaped like a boot?", ["Italy", "Greece", "Spain", "Portugal"], "Sicily sits just off the “toe.”"],
      ko: ["장화 모양으로 유명한 나라는?", ["이탈리아", "그리스", "스페인", "포르투갈"], "‘장화 앞코’ 바로 앞에 시칠리아섬이 있습니다."] },
    { lvl: 1,
      en: ["What is the capital of Brazil?", ["Brasília", "Rio de Janeiro", "São Paulo", "Salvador"], "It replaced Rio de Janeiro as capital in 1960."],
      ko: ["브라질의 수도는?", ["브라질리아", "리우데자네이루", "상파울루", "사우바도르"], "1960년 리우데자네이루에서 수도를 옮겼습니다."] },
    { lvl: 1,
      en: ["What is the largest continent?", ["Asia", "Africa", "North America", "Europe"], "It holds about 30% of the world's land."],
      ko: ["가장 큰 대륙은?", ["아시아", "아프리카", "북아메리카", "유럽"], "전 세계 육지의 약 30%를 차지합니다."] },
    { lvl: 1,
      en: ["In which country is Mount Kilimanjaro?", ["Tanzania", "Kenya", "Uganda", "Ethiopia"], "At 5,895 m it is Africa's highest mountain."],
      ko: ["킬리만자로산이 있는 나라는?", ["탄자니아", "케냐", "우간다", "에티오피아"], "5,895 m로 아프리카에서 가장 높은 산입니다."] },
    { lvl: 1,
      en: ["Which ocean lies between Africa and Australia?", ["Indian Ocean", "Pacific Ocean", "Atlantic Ocean", "Southern Ocean"], "It is the third-largest ocean."],
      ko: ["아프리카와 오스트레일리아 사이에 있는 대양은?", ["인도양", "태평양", "대서양", "남극해"], "세 번째로 큰 대양입니다."] },
    { lvl: 1,
      en: ["What is the capital of Egypt?", ["Cairo", "Alexandria", "Luxor", "Giza"], "It lies on the Nile, near the pyramids of Giza."],
      ko: ["이집트의 수도는?", ["카이로", "알렉산드리아", "룩소르", "기자"], "나일강 변에 있으며 기자 피라미드와 가깝습니다."] },
    { lvl: 1,
      en: ["The Great Barrier Reef lies off the coast of which country?", ["Australia", "New Zealand", "Philippines", "Indonesia"], "It is the world's largest coral reef system."],
      ko: ["그레이트배리어리프가 있는 나라는?", ["오스트레일리아", "뉴질랜드", "필리핀", "인도네시아"], "세계에서 가장 큰 산호초 지대입니다."] },
    { lvl: 1,
      en: ["Which strait lies between Korea and Japan?", ["Korea Strait", "Strait of Malacca", "Taiwan Strait", "Bering Strait"], "It links the East Sea with the East China Sea."],
      ko: ["한국과 일본 사이에 있는 해협은?", ["대한해협", "말라카 해협", "타이완 해협", "베링 해협"], "동해와 동중국해를 잇습니다."] },

    // ---------- Hard ----------
    { lvl: 2,
      en: ["Where is the deepest known point in the ocean?", ["Mariana Trench", "Tonga Trench", "Puerto Rico Trench", "Java Trench"], "The Challenger Deep is about 10,900 m deep."],
      ko: ["바다에서 가장 깊은 지점이 있는 곳은?", ["마리아나 해구", "통가 해구", "푸에르토리코 해구", "자와 해구"], "챌린저 해연의 깊이는 약 10,900 m입니다."] },
    { lvl: 2,
      en: ["What is the capital of Kazakhstan?", ["Astana", "Almaty", "Tashkent", "Bishkek"], "The capital moved from Almaty in 1997."],
      ko: ["카자흐스탄의 수도는?", ["아스타나", "알마티", "타슈켄트", "비슈케크"], "1997년 알마티에서 수도를 옮겼습니다."] },
    { lvl: 2,
      en: ["What is the largest lake in the world by area?", ["Caspian Sea", "Lake Superior", "Lake Victoria", "Lake Baikal"], "Despite its name, it is a lake."],
      ko: ["면적이 가장 넓은 호수는?", ["카스피해", "슈피리어호", "빅토리아호", "바이칼호"], "이름은 ‘해’지만 호수입니다."] },
    { lvl: 2,
      en: ["What is the deepest lake in the world?", ["Lake Baikal", "Lake Tanganyika", "Lake Superior", "Caspian Sea"], "It is over 1,600 m deep and holds about 20% of the world's unfrozen fresh water."],
      ko: ["세계에서 가장 깊은 호수는?", ["바이칼호", "탕가니카호", "슈피리어호", "카스피해"], "깊이 1,600 m가 넘으며, 얼지 않은 지구 담수의 약 20%를 담고 있습니다."] },
    { lvl: 2,
      en: ["Counting overseas territories, which country has the most time zones?", ["France", "Russia", "United States", "United Kingdom"], "France spans 12 time zones."],
      ko: ["해외 영토를 포함할 때 시간대가 가장 많은 나라는?", ["프랑스", "러시아", "미국", "영국"], "프랑스는 12개의 시간대에 걸쳐 있습니다."] },
    { lvl: 2,
      en: ["What is the driest non-polar desert on Earth?", ["Atacama", "Sahara", "Namib", "Gobi"], "Some weather stations there have never recorded rain."],
      ko: ["극지방을 제외하고 지구에서 가장 건조한 사막은?", ["아타카마 사막", "사하라 사막", "나미브 사막", "고비 사막"], "칠레에 있으며, 비가 한 번도 기록되지 않은 관측소도 있습니다."] },
    { lvl: 2,
      en: ["What is the capital of New Zealand?", ["Wellington", "Auckland", "Christchurch", "Queenstown"], "Auckland is the largest city, but Wellington is the capital."],
      ko: ["뉴질랜드의 수도는?", ["웰링턴", "오클랜드", "크라이스트처치", "퀸스타운"], "가장 큰 도시는 오클랜드지만 수도는 웰링턴입니다."] },
    { lvl: 2,
      en: ["What is the longest mountain range on land?", ["Andes", "Rocky Mountains", "Himalayas", "Ural Mountains"], "It runs about 7,000 km along South America."],
      ko: ["육지에서 가장 긴 산맥은?", ["안데스산맥", "로키산맥", "히말라야산맥", "우랄산맥"], "남아메리카를 따라 약 7,000 km 이어집니다."] },
    { lvl: 2,
      en: ["Which river carries the most water?", ["Amazon", "Nile", "Congo", "Yangtze"], "It carries about a fifth of all river water flowing into the oceans."],
      ko: ["물의 양(유량)이 가장 많은 강은?", ["아마존강", "나일강", "콩고강", "양쯔강"], "바다로 흘러가는 전체 강물의 약 5분의 1을 차지합니다."] },
    { lvl: 2,
      en: ["Which country has the most lakes?", ["Canada", "Russia", "Finland", "United States"], "It holds more than half of the world's lakes."],
      ko: ["호수가 가장 많은 나라는?", ["캐나다", "러시아", "핀란드", "미국"], "전 세계 호수의 절반 이상이 캐나다에 있습니다."] },
    { lvl: 2,
      en: ["What has been Myanmar's capital since 2006?", ["Naypyidaw", "Yangon", "Mandalay", "Bagan"], "It replaced Yangon as the capital."],
      ko: ["2006년부터 미얀마의 수도는?", ["네피도", "양곤", "만달레이", "바간"], "양곤을 대신해 수도가 되었습니다."] },
    { lvl: 2,
      en: ["Which two countries share the world's longest international border?", ["Canada and the United States", "Russia and Kazakhstan", "Chile and Argentina", "China and Mongolia"], "It is about 8,890 km long, including the Alaska border."],
      ko: ["세계에서 가장 긴 국경을 맞댄 두 나라는?", ["캐나다와 미국", "러시아와 카자흐스탄", "칠레와 아르헨티나", "중국과 몽골"], "알래스카 구간을 포함해 약 8,890 km입니다."] },
    { lvl: 2,
      en: ["Besides Liechtenstein, which is the world's only other doubly landlocked country?", ["Uzbekistan", "Mongolia", "Switzerland", "Bolivia"], "Every neighbour of a doubly landlocked country is itself landlocked."],
      ko: ["리히텐슈타인과 함께 세계에 둘뿐인 ‘이중 내륙국’은?", ["우즈베키스탄", "몽골", "스위스", "볼리비아"], "이중 내륙국은 이웃 나라들도 모두 바다가 없는 나라입니다."] },
    { lvl: 2,
      en: ["Which African country has three capital cities?", ["South Africa", "Nigeria", "Egypt", "Kenya"], "Pretoria (executive), Cape Town (legislative) and Bloemfontein (judicial)."],
      ko: ["수도가 세 곳인 아프리카 나라는?", ["남아프리카 공화국", "나이지리아", "이집트", "케냐"], "프리토리아(행정), 케이프타운(입법), 블룸폰테인(사법)입니다."] },
    { lvl: 2,
      en: ["What is the longest river on the Korean Peninsula?", ["Amnok (Yalu) River", "Nakdong River", "Han River", "Tumen River"], "It is about 800 km long. In South Korea, the Nakdong is the longest."],
      ko: ["한반도에서 가장 긴 강은?", ["압록강", "낙동강", "한강", "두만강"], "길이는 약 800 km입니다. 남한에서는 낙동강이 가장 깁니다."] },
    { lvl: 2,
      en: ["Which country has the longest coastline?", ["Canada", "Indonesia", "Russia", "Norway"], "It has more than 200,000 km of coastline."],
      ko: ["해안선이 가장 긴 나라는?", ["캐나다", "인도네시아", "러시아", "노르웨이"], "해안선 길이가 20만 km가 넘습니다."] },
    { lvl: 2,
      en: ["Aconcagua, the highest mountain outside Asia, is in which country?", ["Argentina", "Chile", "Peru", "Bolivia"], "It is 6,961 m high, in the Andes."],
      ko: ["아시아 밖에서 가장 높은 산인 아콩카과가 있는 나라는?", ["아르헨티나", "칠레", "페루", "볼리비아"], "안데스산맥에 있으며 높이는 6,961 m입니다."] },
    { lvl: 2,
      en: ["The Strait of Gibraltar separates Spain from which country?", ["Morocco", "Algeria", "Tunisia", "Portugal"], "At its narrowest it is about 14 km wide."],
      ko: ["지브롤터 해협은 스페인과 어느 나라 사이에 있나요?", ["모로코", "알제리", "튀니지", "포르투갈"], "가장 좁은 곳의 폭은 약 14 km입니다."] },
    { lvl: 2,
      en: ["Into which sea does the Danube River flow?", ["Black Sea", "Mediterranean Sea", "Baltic Sea", "Adriatic Sea"], "It flows through or along ten countries."],
      ko: ["도나우강(다뉴브강)이 흘러드는 바다는?", ["흑해", "지중해", "발트해", "아드리아해"], "10개 나라를 지나거나 국경을 따라 흐릅니다."] },
    { lvl: 2,
      en: ["Which country contains the largest share of the Amazon rainforest?", ["Brazil", "Peru", "Colombia", "Venezuela"], "About 60% of the rainforest is in Brazil."],
      ko: ["아마존 열대우림이 가장 많이 있는 나라는?", ["브라질", "페루", "콜롬비아", "베네수엘라"], "열대우림의 약 60%가 브라질에 있습니다."] },
  ],
};
